class TrainingData:
    data = [
        # ----- Greetings ----- 50+
        ("hi", "greeting"),
        ("hello", "greeting"),
        ("hey there", "greeting"),
        ("good morning", "greeting"),
        ("good afternoon", "greeting"),
        ("good evening", "greeting"),
        ("what's good?", "greeting"),
        ("hii", "greeting"),
        ("ello", "greeting"),
        ("hllo", "greeting"),
        ("yo", "greeting"),
        ("whatsup?", "greeting"),
        ("what'sup?", "greeting"),
        ("what'sup", "greeting"),
        ("wassup?", "greeting"),
        ("wassup", "greeting"),
        ("sup", "greeting"),
        ("waddup", "greeting"),
        ("yo yo", "greeting"),
        ("hiya", "greeting"),
        ("howdy", "greeting"),
        ("heyy", "greeting"),
        ("heyya", "greeting"),
        ("helloo", "greeting"),
        ("g'mornin", "greeting"),
        ("gud afternoon", "greeting"),
        ("gud evng", "greeting"),
        ("helooo", "greeting"),
        ("whazzup", "greeting"),
        ("wazzup", "greeting"),
        ("yo wassup", "greeting"),
        ("yo bro", "greeting"),
        ("hey dude", "greeting"),
        ("hey man", "greeting"),
        ("sup bro", "greeting"),
        ("yoo", "greeting"),
        ("heyyoo", "greeting"),
        ("hiyaaa", "greeting"),
        ("wadup", "greeting"),
        ("hyy", "greeting"),
        ("oi", "greeting"),
        ("yo what's good", "greeting"),
        ("eyy", "greeting"),
        ("ehlo", "greeting"),
        ("heelo", "greeting"),
        ("gud mrng", "greeting"),
        ("morningg", "greeting"),
        ("aftrnoon", "greeting"),
        ("evning", "greeting"),
        ("yo fam", "greeting"),
        ("hey pal", "greeting"),


        
       
        # ----- small talks -----
        # ----- asking how are u ----- 33
        ("how are you?", "small_talk"),
        ("u doing good?", "small_talk"),
        ("you good?", "small_talk"),
        ("how's your day?", "small_talk"),
        ("hru", "small_talk"),
        ("hru doing", "small_talk"),
        ("man u good?", "small_talk"),
        ("hope you are doing fine", "small_talk"),
        ("hope ur fine", "small_talk"),
        ("hoping you good", "small_talk"),
        ("hoping you are doing good", "small_talk"),
        ("how r u?", "small_talk"),
        ("how u?", "small_talk"),
        ("how u doing?", "small_talk"), 
        ("how u doin?", "small_talk"),
        ("hows u?", "small_talk"),
        ("how's u?", "small_talk"),
        ("u aight?", "small_talk"),
        ("u good fam?", "small_talk"),
        ("how's life treating u?", "small_talk"),
        ("how's everything?", "small_talk"),
        ("how's things?", "small_talk"),
        ("how's it hanging?", "small_talk"),
        ("what's good with u?", "small_talk"),
        ("u chillin?", "small_talk"),
        ("how's ur day going?", "small_talk"),
        ("how's ur day been?", "small_talk"),
        ("u surviving?", "small_talk"),
        ("how u feeling?", "small_talk"),
        ("how's ur mood?", "small_talk"),
        ("how's tricks?", "small_talk"),
        ("what's poppin?", "small_talk"),
        ("how's the vibes?", "small_talk"),
        ("how u been keeping?", "small_talk"),

        
        
        
        
       
        
        
        # ----- Farewell ----- 30
        ("bye", "farewell"),
        ("see you", "farewell"),
        ("catch you later", "farewell"),
        ("I'm out", "farewell"),
        ("peace out", "farewell"),
        ("byee", "farewell"),
        ("tata", "farewell"),
        ("bubbye", "farewell"),
        ("see ya", "farewell"),
        ("seeya", "farewell"),
        ("later", "farewell"),
        ("laters", "farewell"),
        ("see ya later", "farewell"),
        ("cya", "farewell"),
        ("c u", "farewell"),
        ("cya l8r", "farewell"),
        ("gotta go", "farewell"),
        ("gtg", "farewell"),
        ("g2g", "farewell"),
        ("i'm off", "farewell"),
        ("i'm gone", "farewell"),
        ("outta here", "farewell"),
        ("take care", "farewell"),
        ("cheers", "farewell"),
        ("toodles", "farewell"),
        ("imma bounce", "farewell"),
        ("im outta here", "farewell"),
        ("peace", "farewell"),
        ("bye bye", "farewell"),
        ("see ya soon", "farewell"),


        # ----- oky -----
        ("ok", "agree_query"),
        ("gotcha", "agree_query"),
        ("got it", "agree_query"),
        ("understood", "agree_query"),
        ("okay", "agree_query"),
        ("kay", "agree_query"),
        ("gotit", "agree_query"),
        ("oky i understand", "agree_query"),
        ("i see", "agree_query"),
        ("sorted", "agree_query"),
        ("i understand", "agree_query"),
        ("oky", "agree_query"),
        ("agree", "agree_query"),
        ("agreeeee", "agree_query"),
        ("agreed", "agree_query"),
        ("alright", "agree_query"),
        ("aight", "agree_query"),
        ("okie", "agree_query"),
        ("okie dokie", "agree_query"),
        ("okk", "agree_query"),
        ("okkk", "agree_query"),
        ("okayy", "agree_query"),
        ("roger that", "agree_query"),
        ("copy that", "agree_query"),
        ("got u", "agree_query"),
        ("cool", "agree_query"),
        ("sounds good", "agree_query"),
        ("makes sense", "agree_query"),
        ("yea got it", "agree_query"),
        ("yes i understand", "agree_query"),
        ("yup got it", "agree_query"),
        ("yep okay", "agree_query"),
        ("true that", "agree_query"),
        ("noted", "agree_query"),
        ("noted with thanks", "agree_query"),



        # confused


        # ----- Confused ----- 30
        ("what?", "confused"),
        ("huh?", "confused"),
        ("wait what?", "confused"),
        ("i don't get it", "confused"),
        ("don't understand", "confused"),
        ("idk what you mean", "confused"),
        ("wut", "confused"),
        ("confused", "confused"),
        ("i'm confused", "confused"),
        ("bruh what", "confused"),
        ("bro what r u saying", "confused"),
        ("what does that mean?", "confused"),
        ("can u explain?", "confused"),
        ("sorry huh?", "confused"),
        ("umm what?", "confused"),
        ("not sure i follow", "confused"),
        ("this is confusing", "confused"),
        ("you lost me", "confused"),
        ("what u mean?", "confused"),
        ("eh?", "confused"),
        ("wait im lost", "confused"),
        ("no clue", "confused"),
        ("what r u talkin bout?", "confused"),
        ("this makes no sense", "confused"),
        ("im not gettin it", "confused"),
        ("uhhh?", "confused"),
        ("come again?", "confused"),
        ("what do u mean?", "confused"),
        ("explain pls", "confused"),
        ("sorry, wut?", "confused"),



        
        # ----- Weather Queries -----
        # General 56
        ("weather report", "weather_query"),
        ("weather forecast", "weather_query"),
        ("what's the weather?", "weather_query"),
        ("tell me the weather", "weather_query"),
        ("how's the weather looking?", "weather_query"),
        ("tell weather", "weather_query"),
        ("wether", "weather_query"),
        ("weather good today?", "weather_query"),
        ("weather good?", "weather_query"),
        ("weather ok?", "weather_query"),
        ("how weather?", "weather_query"),
        ("how today weather?", "weather_query"),
        ("today weather?", "weather_query"),
        ("today?", "weather_query"),
        ("today good outside?", "weather_query"),
        ("what is weather saying?", "weather_query"),
        ("what is weather telling?", "weather_query"),
        ("weather looking today?", "weather_query"),
        ("what's the weather like?", "weather_query"),
        ("tell me the weather", "weather_query"),
        ("how's the weather today?", "weather_query"),
        ("is the weather fine?", "weather_query"),
        ("how is weather outside?", "weather_query"),
        ("weather now?", "weather_query"),
        ("today's weather?", "weather_query"),
        ("update on weather?", "weather_query"),
        ("is weather nice?", "weather_query"),
        ("how's the day outside?", "weather_query"),
        ("how's the climate?", "weather_query"),
        ("what's outside like?", "weather_query"),
        ("weather looking fine?", "weather_query"),
        ("any changes in weather?", "weather_query"),
        ("do i need warm clothes?", "weather_query"),
        ("is the weather okay to go out?", "weather_query"),
        ("current weather?", "weather_query"),
        ("can i go outside today?", "weather_query"),
        ("weather looking clear?", "weather_query"),
        ("how's it outside today?", "weather_query"),
        ("how's the condition outside?", "weather_query"),
        ("weather update please", "weather_query"),
        ("how's the atmosphere?", "weather_query"),
        ("is the day pleasant?", "weather_query"),
        ("nice weather today?", "weather_query"),
        ("is it a good weather day?", "weather_query"),
        ("is it decent out today?", "weather_query"),
        ("should i go out today?", "weather_query"),
        ("weather vibe today?", "weather_query"),
        ("any weather news?", "weather_query"),

        
        # Rain-related 47
        ("will it rain later?", "rain_query"),
        ("is it going to rain tonight?", "rain_query"),
        ("chance of rain today?", "rain_query"),
        ("do I need a raincoat?", "rain_query"),
        ("raincoat?", "rain_query"),
        ("rain", "rain_query"),
        ("raining?", "rain_query"),
        ("raining outside?", "rain_query"),
        ("should i take umbrella?", "rain_query"),
        ("umbrella?", "rain_query"),
        ("could it rain?", "rain_query"),
        ("tell about rain", "rain_query"),
        ("is it raining right now?", "rain_query"),
        ("is there rain today?", "rain_query"),
        ("rain expected?", "rain_query"),
        ("any rain today?", "rain_query"),
        ("will there be rain?", "rain_query"),
        ("is it gonna rain?", "rain_query"),
        ("gonna rain today?", "rain_query"),
        ("do i need an umbrella?", "rain_query"),
        ("raining now?", "rain_query"),
        ("will it rain soon?", "rain_query"),
        ("should i expect rain?", "rain_query"),
        ("rain chances?", "rain_query"),
        ("rain forecast?", "rain_query"),
        ("might rain?", "rain_query"),
        ("rain outside?", "rain_query"),
        ("rain alert?", "rain_query"),
        ("rain coming?", "rain_query"),
        ("is rain on the way?", "rain_query"),
        ("rainy day?", "rain_query"),
        ("do i need to prepare for rain?", "rain_query"),
       
        ("are we getting rain today?", "rain_query"),
        ("do I need boots today?", "rain_query"),
        ("is it pouring outside?", "rain_query"),
        ("should I avoid going out because of rain?", "rain_query"),
        ("is the weather wet today?", "rain_query"),
        ("any rain alerts for today?", "rain_query"),
        ("will there be heavy showers?", "rain_query"),
        ("is there drizzle outside?", "rain_query"),
        ("are storms expected today?", "rain_query"),
        ("is it expected to drizzle?", "rain_query"),
        ("do I need waterproof stuff?", "rain_query"),
        ("should I carry an umbrella just in case?", "rain_query"),
        ("how's the rain situation?", "rain_query"),
        ("can I expect clear skies or rain?", "rain_query"),
        ("should I prep for rain?", "rain_query"),



        
        # Temperature  36
        ("what's the temp?", "temp_query"),
        ("how hot is it today?", "temp_query"),
        ("is it cold outside?", "temp_query"),
        ("current temperature please", "temp_query"),
        ("temp", "temp_query"),
        ("temp outside", "temp_query"),
        ("temp today", "temp_query"),
        ("temperature today", "temp_query"),
        ("temperature outside", "temp_query"),
        ("temperature", "temp_query"),
        ("hot today?", "temp_query"),
        ("cold today?", "temp_query"),
        ("cold?", "temp_query"),
        ("hot?", "temp_query"),
        ("tell temperature", "temp_query"),
        ("tell temp", "temp_query"),
        ("how's the temperature?", "temp_query"),
        ("what's the temperature rn?", "temp_query"),
        ("how warm is it?", "temp_query"),
        ("is it warm today?", "temp_query"),
        ("is it freezing outside?", "temp_query"),
        ("is it chilly?", "temp_query"),
        ("is it hot out?", "temp_query"),
        ("how's the heat?", "temp_query"),
        ("how's the cold today?", "temp_query"),
        ("temp rn?", "temp_query"),
        ("current temp?", "temp_query"),
        ("any idea of temp?", "temp_query"),
        ("what temp now?", "temp_query"),
        ("what's it like outside? hot or cold?", "temp_query"),
        ("should i wear warm clothes?", "temp_query"),
        ("do i need a jacket today?", "temp_query"),
        ("is the temp okay?", "temp_query"),
        ("is the weather hot?", "temp_query"),
        ("is today cold or hot?", "temp_query"),
        ("how's it feeling out there?", "temp_query"),

        
        # Location-specific  56
        ("weather in London", "location_specific_weather_query"),
        ("what's the weather in Tokyo?", "location_specific_weather_query"),
        ("New York weather forecast", "location_specific_weather_query"),
        ("how's the weather in Dubai right now?", "location_specific_weather_query"),
        ("Dubai weather", "location_specific_weather_query"),
        ("weather in dubai", "location_specific_weather_query"),
        ("weather in karachi", "location_specific_weather_query"),
        ("weather in newyork", "location_specific_weather_query"),
        ("weather forecast for newyork", "location_specific_weather_query"),
        ("weather forecast in newyork", "location_specific_weather_query"),
        ("whats weather in sharjah", "location_specific_weather_query"),
        ("weather in Lahore", "location_specific_weather_query"),
        ("is it hot in Islamabad?", "location_specific_weather_query"),
        ("how's the weather in Paris?", "location_specific_weather_query"),
        ("current weather in Berlin", "location_specific_weather_query"),
        ("temperature in Rome", "location_specific_weather_query"),
        ("show me weather in Delhi", "location_specific_weather_query"),
        ("tell me weather in Mumbai", "location_specific_weather_query"),
        ("forecast in Tokyo", "location_specific_weather_query"),
        ("weather report for Sydney", "location_specific_weather_query"),
        ("weather check for Toronto", "location_specific_weather_query"),
        ("is it raining in London?", "location_specific_weather_query"),
        ("today weather in Seoul", "location_specific_weather_query"),
        ("weather today in Beijing", "location_specific_weather_query"),
        ("what's the weather like in Moscow?", "location_specific_weather_query"),
        ("weather in NYC", "location_specific_weather_query"),
        ("nyc weather?", "location_specific_weather_query"),
        ("how's karachi weather today?", "location_specific_weather_query"),
        ("any update on weather in Chicago?", "location_specific_weather_query"),
        ("forecast for Islamabad", "location_specific_weather_query"),
        ("is it cloudy in San Francisco?", "location_specific_weather_query"),
        ("is it raining in London?", "location_specific_weather_query"),
        ("what's the temperature in Dubai?", "location_specific_weather_query"),
        ("humidity levels in Karachi?", "location_specific_weather_query"),
        ("wind speed in New York?", "location_specific_weather_query"),
        ("is it windy in Lahore?", "location_specific_weather_query"),
        ("is it cold in Islamabad right now?", "location_specific_weather_query"),
        ("will it rain today in Delhi?", "location_specific_weather_query"),
        ("how hot is it in Riyadh?", "location_specific_weather_query"),
        ("what's the air quality in Mumbai?", "location_specific_weather_query"),
        ("what's the weather like in Peshawar?", "location_specific_weather_query"),
        ("sunset time in Paris?", "location_specific_weather_query"),
        ("is it sunny in Sydney right now?", "location_specific_weather_query"),
        ("today's forecast in Toronto?", "location_specific_weather_query"),
        ("is there rain expected in Sharjah?", "location_specific_weather_query"),
        ("how's the climate in Berlin?", "location_specific_weather_query"),
        ("foggy in Beijing today?", "location_specific_weather_query"),
        ("what's the heat level in Cairo?", "location_specific_weather_query"),
        ("does it feel humid in Bangkok?", "location_specific_weather_query"),
        ("current wind condition in San Francisco?", "location_specific_weather_query"),
        ("will it be cloudy in Seoul today?", "location_specific_weather_query"),


        
        # Clothing advice 28
        ("should I wear a jacket today?", "clothing_advice"),
        ("do I need sunglasses?", "clothing_advice"),
        ("is it shorts weather?", "clothing_advice"),
        ("what to wear", "clothing_advice"),
        ("should i wear this?", "clothing_advice"),
        ("should i wear pent coat", "clothing_advice"),
        ("should i wear shirt", "clothing_advice"),
        ("should i wear T-shirt", "clothing_advice"),
        ("okay to wear this", "clothing_advice"),
        ("okay to wear", "clothing_advice"),
        ("okay to wear T-shirt?", "clothing_advice"),
        ("clothing advice?", "clothing_advice"),
        ("help me cloth", "clothing_advice"),
        ("what should I wear today?", "clothing_advice"),
        ("do I need a jacket?", "clothing_advice"),
        ("is it shorts weather?", "clothing_advice"),  
        ("outfit for rainy day", "clothing_advice"),
        ("winter clothes needed?", "clothing_advice"),
        ("should I wear layers today?", "clothing_advice"),
        ("is this too heavy for the weather?", "clothing_advice"),
        ("would a sweater be enough?", "clothing_advice"),
        ("do I need thermal wear?", "clothing_advice"),
        ("jacket or hoodie for today?", "clothing_advice"),
        ("are flip-flops okay today?", "clothing_advice"),
        ("should I pack an extra layer?", "clothing_advice"),
        ("is a rain jacket necessary?", "clothing_advice"),
        ("can I wear sandals?", "clothing_advice"),
        ("what footwear works best?", "clothing_advice"),
        
        # ----- Negative Responses ----- 36
        ("no weather needed", "neg_res"),
        ("stop weather updates", "neg_res"),
        ("I don't care about weather", "neg_res"),
        ("never mind the weather", "neg_res"),
        ("cancel weather request", "neg_res"),
        ("don't", "neg_res"),
        ("don't need help", "neg_res"),
        ("don't need you", "neg_res"),
        ("no need of you", "neg_res"),
        ("no not needed", "neg_res"),
        ("not", "neg_res"),
        ("go away", "neg_res"),
        ("you are pathetic", "neg_res"),
        ("you are looser", "neg_res"),
        ("cancel", "neg_res"),
        ("no thanks", "neg_res"),
        ("nah I'm good", "neg_res"),
        ("nope", "neg_res"),
        ("leave me alone", "neg_res"),
        ("not interested", "neg_res"),
        ("I don't want that", "neg_res"),
        ("that's useless", "neg_res"),
        ("you're no help", "neg_res"),
        ("don't want it", "neg_res"),
        ("get lost", "neg_res"),
        ("not needed", "neg_res"),
        ("useless bot", "neg_res"),
        ("you're annoying", "neg_res"),
        ("buzz off", "neg_res"),
        ("i said no", "neg_res"),
        ("nuh uh", "neg_res"),
        ("why are you here?", "neg_res"),
        ("nobody asked", "neg_res"),
        ("don't bother", "neg_res"),
        ("shut it", "neg_res"),

        
        
        # Humidity 25
        ("what's the humidity?", "humid_query"),
        ("is it humid today?", "humid_query"),
        ("humidity level please", "humid_query"),
        ("humidity", "humid_query"),
        ("tell humidity", "humid_query"),
        ("is the air humid?", "humid_query"),
        ("how humid is it today?", "humid_query"),
        ("humidity rn?", "humid_query"),
        ("current humidity level?", "humid_query"),
        ("high humidity today?", "humid_query"),
        ("low humidity?", "humid_query"),
        ("what's the humidity like?", "humid_query"),
        ("air moisture today?", "humid_query"),
        ("how's the humidity outside?", "humid_query"),
        ("is it sticky out there?", "humid_query"),
        ("is it muggy today?", "humid_query"),
        ("muggy outside?", "humid_query"),
        ("is the weather humid?", "humid_query"),
        ("humid or dry?", "humid_query"),
        ("do i need moisturizer today?", "humid_query"),
        ("feels humid", "humid_query"),
        ("humidity levels plz", "humid_query"),
        ("humid out?", "humid_query"),
        ("humidity percent?", "humid_query"),
        ("can u tell humidity?", "humid_query"),

        
        # Wind 27
        ("how windy is it?", "wind_query"),
        ("wind speed today", "wind_query"),
        ("is it breezy outside?", "wind_query"),
        ("wind now", "wind_query"),
        ("wind?", "wind_query"),
        ("wind today", "wind_query"),
        ("windy", "wind_query"),
        ("is it windy rn?", "wind_query"),
        ("how's the wind today?", "wind_query"),
        ("super windy outside?", "wind_query"),
        ("is it breezy today?", "wind_query"),
        ("windy out there?", "wind_query"),
        ("do i need a jacket for the wind?", "wind_query"),
        ("crazy wind today?", "wind_query"),
        ("windy af?", "wind_query"),
        ("blowing hard outside?", "wind_query"),
        ("how strong is the wind?", "wind_query"),
        ("wind chill today?", "wind_query"),
        ("is the wind bad?", "wind_query"),
        ("can you feel the wind?", "wind_query"),
        ("windy or calm today?", "wind_query"),
        ("is it calm outside?", "wind_query"),
        ("wind's picking up?", "wind_query"),
        ("gonna be windy later?", "wind_query"),
        ("wind speed plz", "wind_query"),
        ("should i worry about wind?", "wind_query"),
        ("what's the wind saying?", "wind_query"),

        
        
        
        # UV/Sun 30
        ("what's the UV index?", "sun_query"),
        ("is it sunny right now?", "sun_query"),
        ("when is sunset today?", "sun_query"),
        ("sunrise time please", "sun_query"),
        ("sunrise when?", "sun_query"),
        ("sunrise wen", "sun_query"),
        ("when sunrise", "sun_query"),
        ("sunset when?", "sun_query"),
        ("sunset wen", "sun_query"),
        ("when sunset", "sun_query"),
        ("what time is sunset?", "sun_query"),
        ("what time is sunrise?", "sun_query"),
        ("is it sunny rn?", "sun_query"),
        ("sun out right now?", "sun_query"),
        ("is the sun up?", "sun_query"),
        ("is it still sunny?", "sun_query"),
        ("how strong is the sun?", "sun_query"),
        ("sun shining?", "sun_query"),
        ("uv index today?", "sun_query"),
        ("do i need sunscreen today?", "sun_query"),
        ("sun too harsh today?", "sun_query"),
        ("sun setting soon?", "sun_query"),
        ("has the sun risen yet?", "sun_query"),
        ("is it bright outside?", "sun_query"),
        ("sunset time today?", "sun_query"),
        ("sunrise today?", "sun_query"),
        ("sunlight now?", "sun_query"),
        ("uv right now?", "sun_query"),
        ("is uv high today?", "sun_query"),
        ("what's the sunlight like?", "sun_query"),

        
        # Air Quality 24
        ("air quality today", "air_query"),
        ("is the air polluted?", "air_query"),
        ("pollen count today", "air_query"),
        ("pollution", "air_query"),
        ("how's the air today?", "air_query"),
        ("air quality rn?", "air_query"),
        ("is the air safe to breathe?", "air_query"),
        ("should I wear a mask outside?", "air_query"),
        ("how bad is the pollution today?", "air_query"),
        ("pollution level rn?", "air_query"),
        ("current AQI?", "air_query"),
        ("what's the AQI today?", "air_query"),
        ("air feels bad today?", "air_query"),
        ("is it dusty outside?", "air_query"),
        ("breathable air today?", "air_query"),
        ("can I jog today? how's the air?", "air_query"),
        ("pollen levels now?", "air_query"),
        ("should I avoid going out?", "air_query"),
        ("smoggy outside?", "air_query"),
        ("is air quality okay?", "air_query"),
        ("air pollution update?", "air_query"),
        ("is it smoky today?", "air_query"),
        ("safe to go for a walk?", "air_query"),
        ("tell me about air conditions", "air_query"),

        
        # Activity Suggestions
        #---walking 28
        ("is it good weather for walking?", "walk_query"),
        ("best time to walking?", "walk_query"),
        ("good to walking?", "walk_query"),
        ("when walk?", "walk_query"),
        ("walk?", "walk_query"),
        ("walk", "walk_query"),
        ("going to walk", "walk_query"),
        ("can I go for a walk now?", "walk_query"),
        ("is it nice outside for a walk?", "walk_query"),
        ("should I go walking now?", "walk_query"),
        ("weather okay for walking?", "walk_query"),
        ("walking possible now?", "walk_query"),
        ("how's the walking weather?", "walk_query"),
        ("is now a good time for a walk?", "walk_query"),
        ("safe to walk now?", "walk_query"),
        ("want to walk outside, is it good?", "walk_query"),
        ("is it too hot to walk?", "walk_query"),
        ("can I walk outside today?", "walk_query"),
        ("can I go for a stroll?", "walk_query"),
        ("walk-friendly weather?", "walk_query"),
        ("i wanna walk", "walk_query"),
        ("thinking to walk, good idea?", "walk_query"),
        ("walk weather rn?", "walk_query"),
        ("should I skip my walk?", "walk_query"),
        ("good day to walk?", "walk_query"),
        ("walking time?", "walk_query"),
        ("is it chill for walking?", "walk_query"),
        ("alright to walk?", "walk_query"),

        #---cycle 25
        ("can I cycle today?", "cycle_query"),
        ("cycle", "cycle_query"),
        ("cycling today good?", "cycle_query"),
        ("cycling when?", "cycle_query"),
        ("okay to cycle", "cycle_query"),
        ("is it good for biking?", "cycle_query"),
        ("can I ride today?", "cycle_query"),
        ("how's the cycling weather?", "cycle_query"),
        ("ride my bike now?", "cycle_query"),
        ("safe to cycle today?", "cycle_query"),
        ("bike weather okay?", "cycle_query"),
        ("can I take the cycle out?", "cycle_query"),
        ("too windy to cycle?", "cycle_query"),
        ("can I go biking?", "cycle_query"),
        ("cycling time?", "cycle_query"),
        ("should I go cycle now?", "cycle_query"),
        ("want to go biking", "cycle_query"),
        ("planning to cycle today", "cycle_query"),
        ("bike ride good?", "cycle_query"),
        ("any alerts for cycling?", "cycle_query"),
        ("is cycling a good idea now?", "cycle_query"),
        ("how's it for cycling?", "cycle_query"),
        ("ok weather to cycle?", "cycle_query"),
        ("going to ride, all good?", "cycle_query"),
        ("bike or no bike today?", "cycle_query"),

        #---outing 25
        ("good day for a picnic?", "outing_query"),
        ("good day for a outing?", "outing_query"),
        ("good day for day to go out?", "outing_query"),
        ("picnic?", "outing_query"),
        ("planing outing good?", "outing_query"),
        ("is it a good day to go out?", "outing_query"),
        ("should we go for a picnic?", "outing_query"),
        ("outing weather okay?", "outing_query"),
        ("can I go out today?", "outing_query"),
        ("how's the day for a trip?", "outing_query"),
        ("planning to chill outside, good?", "outing_query"),
        ("day trip today possible?", "outing_query"),
        ("outing weather?", "outing_query"),
        ("can I go out for fun?", "outing_query"),
        ("too hot for outing?", "outing_query"),
        ("safe to go out now?", "outing_query"),
        ("good day to hang out?", "outing_query"),
        ("i wanna go out today", "outing_query"),
        ("can we go out now?", "outing_query"),
        ("outing vibes today?", "outing_query"),
        ("sunny enough for a picnic?", "outing_query"),
        ("chilling outside okay?", "outing_query"),
        ("plan an outing?", "outing_query"),
        ("outing possible?", "outing_query"),
        ("go out with friends today?", "outing_query"),

        
        # ----- Help ----- 30
        ("help", "help"),
        ("what can you do?", "help"),
        ("list commands", "help"),
        ("how does this work?", "help"),
        ("can u help", "help"),
        ("welpp", "help"),
        ("welppppp", "help"),
        ("helppp", "help"),
        ("save me", "help"),
        ("need help", "help"),
        ("i need some help", "help"),
        ("how can you assist me?", "help"),
        ("what do you know?", "help"),
        ("show me what you can do", "help"),
        ("can you help me out?", "help"),
        ("any help?", "help"),
        ("how do I use you?", "help"),
        ("what features do you support?", "help"),
        ("how to talk to you?", "help"),
        ("how to use this bot?", "help"),
        ("i need support", "help"),
        ("stuck here, help?", "help"),
        ("emergency help", "help"),
        ("guide me", "help"),
        ("explain how this works", "help"),
        ("i'm confused, help", "help"),
        ("tell me what you do", "help"),
        ("u there? help", "help"),
        ("pls help", "help"),
        ("need assistant", "help"),

        
        # ----- Mood/Feeling -----
        # ----- Mood/good ----- 25
        ("I feel great today", "mood_good"),
        ("I'm feeling awesome", "mood_good"),
        ("I'm feeling good", "mood_good"),
        ("mood good", "mood_good"),
        ("not feeling good", "mood_bad"),
        ("feeling amazing today", "mood_good"),
        ("i'm happy", "mood_good"),
        ("i'm in a good mood", "mood_good"),
        ("today is going well", "mood_good"),
        ("vibing good today", "mood_good"),
        ("i'm cheerful", "mood_good"),
        ("i feel fresh", "mood_good"),
        ("mentally relaxed", "mood_good"),
        ("i'm in high spirits", "mood_good"),
        ("feelin great", "mood_good"),
        ("today's a good day", "mood_good"),
        ("i'm doing just fine", "mood_good"),
        ("i'm chill today", "mood_good"),
        ("everything feels right", "mood_good"),
        ("i feel like smiling", "mood_good"),
        ("happy mood", "mood_good"),
        ("my vibe is good", "mood_good"),
        ("i'm grateful today", "mood_good"),
        ("feeling good vibes", "mood_good"),
        ("mentally feeling better", "mood_good"),

        # ----- Mood/bad ----- 27
        ("I feel terrible", "mood_bad"),
        ("I'm so sad right now", "mood_bad"),
        ("feeling bad", "mood_bad"),
        ("sadness", "mood_bad"),
        ("sad feeeling", "mood_bad"),
        ("sad feeeling why?", "mood_bad"),
        ("mood not good", "mood_bad"),
        ("i feel off today", "mood_bad"),
        ("i'm not okay", "mood_bad"),
        ("i'm feeling low", "mood_bad"),
        ("not in the mood", "mood_bad"),
        ("today's rough", "mood_bad"),
        ("mental health bad rn", "mood_bad"),
        ("i feel tired of everything", "mood_bad"),
        ("i feel drained", "mood_bad"),
        ("i feel broken", "mood_bad"),
        ("feeling anxious", "mood_bad"),
        ("not my day", "mood_bad"),
        ("i feel down", "mood_bad"),
        ("emotionally not fine", "mood_bad"),
        ("i'm overwhelmed", "mood_bad"),
        ("i feel empty", "mood_bad"),
        ("sad mood today", "mood_bad"),
        ("can't focus, bad mood", "mood_bad"),
        ("really down right now", "mood_bad"),
        ("don't feel good mentally", "mood_bad"),
        ("just not okay", "mood_bad")

    ]